version: '3.8'

services:
  app:
    env_file: .env
    build: .
    ports:
      - "${APP_PORT}:${APP_PORT}"
    environment:
      - APP_NAME=${APP_NAME} 
      - NODE_ENV=${NODE_ENV}
      - ELASTICSEARCH_HOST=${ELASTICSEARCH_HOST}
      - ELASTIC_APM_SERVER_URL=${ELASTIC_APM_SERVER_URL}
      - ELASTIC_APM_SECRET_TOKEN= ${ELASTIC_APM_SECRET_TOKEN}
      - ELASTIC_APM_ACTIVE=${ELASTIC_APM_ACTIVE}
      - ELASTICSEARCH_INDEX=${ELASTICSEARCH_INDEX}
    depends_on:
      - elasticsearch
    volumes:
      - .:/app
      - /app/node_modules

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.4
    ports:
      - "5601:5601"
    environment:
      ELASTICSEARCH_URL: http://elasticsearch:9200
    depends_on:
      - elasticsearch
    
  apm-server:
    image: docker.elastic.co/apm/apm-server:8.17.0
    ports:
      - "8200:8200"
    environment:
      - output.elasticsearch.hosts=["elasticsearch:9200"]
      - apm-server.rum.enabled=true
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data: